ALTER TABLE "PricingTier" ADD COLUMN IF NOT EXISTS "registerClose" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PricingTier" ADD COLUMN IF NOT EXISTS "isGroup" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PricingTier" ADD COLUMN IF NOT EXISTS "groupSize" INTEGER;
